### ISSUE TITLE
PDF Viewer not available when pdfs are added to meta data post hoc

### ISSUE THREAD

**Issue by patebel** [sysrev/sysrev#1]
Thanks for supplying system with its basic functionality for free! 

However, I experience the following issue: If you upload an XML with paper meta data first and then add the pdfs individually, you cannot view the pdf in the coding window but only see the title and abstract and can only download the .pdf. Any chance to change this and show the .pdf in the viewer independent of how it was uploaded? 

Thanks!

**Comment by john-shaffer** [comment]
Thank you for the report.

We have added the PDF tab (show below) for some article types that didn't have it. Is it working for you now?
![image](https://github.com/sysrev/sysrev/assets/53870456/ba696fad-277e-40eb-8367-ce2a14777939)

**Comment by patebel** [comment]
Yes, thank you so much!
