### ISSUE TITLE
.xlsx export does not contain Article Title, Title, Authors, Journal information

### ISSUE THREAD

**Issue by patebel** [sysrev/sysrev#3]
Dear Team,

We are currently reviewing in a two-step process and have uploaded the .ris file generated by sysrev as input for the second step. However, when we export the results from stage 2, these fields are blank in the .xlsx file, even though this information is available in sysrev. This makes it impossible for us to match the stage 2 results with the stage 1 results.

Would be very thankful for any help!

**Comment by john-shaffer** [comment]
This should be fixed now. Is it working for you?

**Comment by patebel** [comment]
Hi John, thanks for the quick reply. I just checked it and while Journal and Authors are available now, Article Title and Title still aren't.

**Comment by john-shaffer** [comment]
Can you add a link to the project?

**Comment by patebel** [comment]
Sure: https://sysrev.com/p/124810

**Comment by john-shaffer** [comment]
This is fixed now. Since Article Title was the same thing as Title, we also changed it to Article URL to match the other exports. Thank you!

**Comment by patebel** [comment]
Perfect, works fine now! Thanks :)
