### ISSUE TITLE
Data Export not working

### ISSUE THREAD

**Issue by patebel** [sysrev/sysrev#7]
Dear Team, 

Currently it's not possible to export data from projects. After clicking "Generate", the loading indicator stays forever and the system seems to be stuck in generating the file.

Any help would be appreciated!

**Comment by john-shaffer** [comment]
Thanks for the notice. Exports should be working again. We had an issue where a new feature was using up all capacity, preventing other tasks from being run.

**Comment by patebel** [comment]
Yes, it works again. Thanks!
